# H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  # MariaDB
  datasource:
    url: jdbc:mariadb://dev-devdevdev-rdb.ch4mmisoklo6.ap-northeast-2.rds.amazonaws.com:3306/devdevdev?rewriteBatchedStatements=true
    username: dreamy5patisiel
    password: 5Patisiel!!6522maria
    driver-class-name: org.mariadb.jdbc.Driver
